//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avav
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Запись.
    /// </summary>
    // *** Start programmer edit section *** (Запись CustomAttributes)

    // *** End programmer edit section *** (Запись CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаписьE", new string[] {
            "Время as \'Время\'",
            "Клиент as \'Клиент\'",
            "Клиент.имя as \'Имя\'"}, Hidden=new string[] {
            "Клиент.имя"})]
    [MasterViewDefineAttribute("ЗаписьE", "Клиент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "имя")]
    [View("ЗаписьL", new string[] {
            "Время as \'Время\'",
            "Клиент.имя as \'Имя\'"})]
    public class Запись : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fВремя = System.DateTime.Parse("Time");
        
        private IIS.Avav.Клиент fКлиент;
        
        // *** Start programmer edit section *** (Запись CustomMembers)

        // *** End programmer edit section *** (Запись CustomMembers)

        
        /// <summary>
        /// Время.
        /// </summary>
        // *** Start programmer edit section *** (Запись.Время CustomAttributes)

        // *** End programmer edit section *** (Запись.Время CustomAttributes)
        public virtual System.DateTime Время
        {
            get
            {
                // *** Start programmer edit section *** (Запись.Время Get start)

                // *** End programmer edit section *** (Запись.Время Get start)
                System.DateTime result = this.fВремя;
                // *** Start programmer edit section *** (Запись.Время Get end)

                // *** End programmer edit section *** (Запись.Время Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.Время Set start)

                // *** End programmer edit section *** (Запись.Время Set start)
                this.fВремя = value;
                // *** Start programmer edit section *** (Запись.Время Set end)

                // *** End programmer edit section *** (Запись.Время Set end)
            }
        }
        
        /// <summary>
        /// Запись.
        /// </summary>
        // *** Start programmer edit section *** (Запись.Клиент CustomAttributes)

        // *** End programmer edit section *** (Запись.Клиент CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент"})]
        [NotNull()]
        public virtual IIS.Avav.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (Запись.Клиент Get start)

                // *** End programmer edit section *** (Запись.Клиент Get start)
                IIS.Avav.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (Запись.Клиент Get end)

                // *** End programmer edit section *** (Запись.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Запись.Клиент Set start)

                // *** End programmer edit section *** (Запись.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (Запись.Клиент Set end)

                // *** End programmer edit section *** (Запись.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаписьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьE", typeof(IIS.Avav.Запись));
                }
            }
            
            /// <summary>
            /// "ЗаписьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьL", typeof(IIS.Avav.Запись));
                }
            }
        }
    }
}
